import esbuild from 'esbuild';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

async function main() {
  const isProduction = process.env.NODE_ENV === 'production';

  const buildContext = await esbuild.context({
    banner: {
      js: banner
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: [
      'obsidian',
      'electron',
      '@codemirror/autocomplete',
      '@codemirror/collab',
      '@codemirror/commands',
      '@codemirror/language',
      '@codemirror/lint',
      '@codemirror/search',
      '@codemirror/state',
      '@codemirror/view',
      '@lezer/common',
      '@lezer/highlight',
      '@lezer/lr',
      ...builtinModules
    ],
    format: 'cjs',
    target: 'es2018',
    logLevel: isProduction ? 'warning' : 'info',
    sourcemap: isProduction ? false : 'inline',
    treeShaking: true,
    outfile: 'dist/main.js',
    minify: isProduction
  });

  if (isProduction) {
    await buildContext.rebuild();
    process.exit(0);
  } else {
    await buildContext.watch();
  }
}

main().then().catch().finally();
