packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': 2.3.7
  '@types/node': ^24.10.1
  '@typescript/native-preview': 7.0.0-dev.20251121.1
  typescript: ^5.9.3

minimumReleaseAge: 10080

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
