/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Obsidian Google Drive Sync
 * OpenAPI spec version: 0.0.0
 */

import { apiClient } from "../../src/ky-client";
import type {
  ExchangeAccessTokenRequest,
  ExchangeAccessTokenResponse,
  HealthcheckResponse,
  InternalServerError,
  ValidationError,
} from "../model";

export type googleDriveAPIExchangeAccessTokenResponse200 = {
  data: ExchangeAccessTokenResponse;
  status: 200;
};

export type googleDriveAPIExchangeAccessTokenResponse400 = {
  data: ValidationError;
  status: 400;
};

export type googleDriveAPIExchangeAccessTokenResponse500 = {
  data: InternalServerError;
  status: 500;
};

export type googleDriveAPIExchangeAccessTokenResponseSuccess =
  googleDriveAPIExchangeAccessTokenResponse200 & {
    headers: Headers;
  };
export type googleDriveAPIExchangeAccessTokenResponseError = (
  | googleDriveAPIExchangeAccessTokenResponse400
  | googleDriveAPIExchangeAccessTokenResponse500
) & {
  headers: Headers;
};

export type googleDriveAPIExchangeAccessTokenResponse =
  | googleDriveAPIExchangeAccessTokenResponseSuccess
  | googleDriveAPIExchangeAccessTokenResponseError;

export const getGoogleDriveAPIExchangeAccessTokenUrl = () => {
  return `/access-token`;
};

export const googleDriveAPIExchangeAccessToken = async (
  exchangeAccessTokenRequest: ExchangeAccessTokenRequest,
  options?: RequestInit,
): Promise<googleDriveAPIExchangeAccessTokenResponse> => {
  return apiClient<googleDriveAPIExchangeAccessTokenResponse>(
    getGoogleDriveAPIExchangeAccessTokenUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(exchangeAccessTokenRequest),
    },
  );
};

export type healthcheckResponse200 = {
  data: HealthcheckResponse;
  status: 200;
};

export type healthcheckResponse400 = {
  data: ValidationError;
  status: 400;
};

export type healthcheckResponse500 = {
  data: InternalServerError;
  status: 500;
};

export type healthcheckResponseSuccess = healthcheckResponse200 & {
  headers: Headers;
};
export type healthcheckResponseError = (healthcheckResponse400 | healthcheckResponse500) & {
  headers: Headers;
};

export type healthcheckResponse = healthcheckResponseSuccess | healthcheckResponseError;

export const getHealthcheckUrl = () => {
  return `/health`;
};

export const healthcheck = async (options?: RequestInit): Promise<healthcheckResponse> => {
  return apiClient<healthcheckResponse>(getHealthcheckUrl(), {
    ...options,
    method: "GET",
  });
};
