/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Obsidian Google Drive Sync
 * OpenAPI spec version: 0.0.0
 */
import type {
  ExchangeAccessTokenRequest,
  ExchangeAccessTokenResponse,
  InternalServerError,
  ValidationError,
} from "../model";

export type googleDriveAPIExchangeAccessTokenResponse200 = {
  data: ExchangeAccessTokenResponse;
  status: 200;
};

export type googleDriveAPIExchangeAccessTokenResponse400 = {
  data: ValidationError;
  status: 400;
};

export type googleDriveAPIExchangeAccessTokenResponse500 = {
  data: InternalServerError;
  status: 500;
};

export type googleDriveAPIExchangeAccessTokenResponseSuccess =
  googleDriveAPIExchangeAccessTokenResponse200 & {
    headers: Headers;
  };
export type googleDriveAPIExchangeAccessTokenResponseError = (
  | googleDriveAPIExchangeAccessTokenResponse400
  | googleDriveAPIExchangeAccessTokenResponse500
) & {
  headers: Headers;
};

export type googleDriveAPIExchangeAccessTokenResponse =
  | googleDriveAPIExchangeAccessTokenResponseSuccess
  | googleDriveAPIExchangeAccessTokenResponseError;

export const getGoogleDriveAPIExchangeAccessTokenUrl = () => {
  return `/access-token`;
};

export const googleDriveAPIExchangeAccessToken = async (
  exchangeAccessTokenRequest: ExchangeAccessTokenRequest,
  options?: RequestInit,
): Promise<googleDriveAPIExchangeAccessTokenResponse> => {
  const res = await fetch(getGoogleDriveAPIExchangeAccessTokenUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(exchangeAccessTokenRequest),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: googleDriveAPIExchangeAccessTokenResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as googleDriveAPIExchangeAccessTokenResponse;
};
