/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Obsidian Google Drive Sync
 * OpenAPI spec version: 0.0.0
 */

/**
 * An access token is a credential issued by the authorization server to the client application, representing the authorization granted by the resource owner to access protected resources (like APIs) on a resource server.
 */
export type AccessToken = string;
