/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Obsidian Google Drive Sync
 * OpenAPI spec version: 0.0.0
 */
import type { AccessToken } from "./access-token";
import type { ExpiresIn } from "./expires-in";

export interface ExchangeAccessTokenResponse {
  accessToken: AccessToken;
  expiresIn: ExpiresIn;
}
