/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Obsidian Google Drive Sync
 * OpenAPI spec version: 0.0.0
 */
import type { RefreshToken } from "./refresh-token";

export interface ExchangeAccessTokenRequest {
  refreshToken: RefreshToken;
}
