/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Obsidian Google Drive Sync
 * OpenAPI spec version: 0.0.0
 */

import type { ErrorMessage } from "./error-message";
import type { InternalServerErrorCode } from "./internal-server-error-code";

export interface InternalServerError {
  code: InternalServerErrorCode;
  message: ErrorMessage;
}
