/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Obsidian Google Drive Sync
 * OpenAPI spec version: 0.0.0
 */

/**
 * A refresh token is a credential used to obtain a new access token when the current one expires, without requiring the user to re-authenticate.
 */
export type RefreshToken = string;
